_wandb:
    value:
        cli_version: 0.21.2
        e:
            abhjw9xlfccs29th2jy1sm3xbwhv1dtt:
                args:
                    - --d_model
                    - "512"
                    - --num_heads
                    - "16"
                    - --d_ff
                    - "1344"
                    - --context_length
                    - "256"
                    - --num_layers
                    - "4"
                    - --device
                    - cpu
                    - --batch_size
                    - "4"
                    - --train_data_path
                    - ../data/test_data.npy
                    - --val_data_path
                    - ../data/test_data.npy
                    - --eval_steps
                    - "9"
                    - --save_steps
                    - "5"
                    - --log_steps
                    - "1"
                codePath: cs336_basics\trainer.py
                codePathLocal: trainer.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "57670627328"
                        used: "53431009280"
                email: 760384579@qq.com
                executable: E:\LLM\CS336\assignment1-basics\.venv\Scripts\python.exe
                git:
                    commit: 6f3e9dda1acb1599142f04f415079dcada14dc8c
                    remote: git@github.com:FlyingFish760/CS336-assignment1-basics.git
                gpu: NVIDIA GeForce MX450
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce MX450
                      uuid: GPU-9fa8c5ee-f6e2-5dc5-e0c0-7b91b322f017
                host: LAPTOP-KNVFV7GR
                memory:
                    total: "16969424896"
                os: Windows-10-10.0.19045-SP0
                program: E:\LLM\CS336\assignment1-basics\cs336_basics\trainer.py
                python: CPython 3.12.9
                root: E:\LLM\CS336\assignment1-basics\cs336_basics
                startedAt: "2025-12-23T08:38:54.365734Z"
                writerId: abhjw9xlfccs29th2jy1sm3xbwhv1dtt
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 16
            "4": 3.12.9
            "5": 0.21.2
            "6": 4.57.3
            "8":
                - 3
            "12": 0.21.2
            "13": windows-amd64
max_learning_rate:
    value: 1e-05
steps:
    value: 9
