_wandb:
    value:
        cli_version: 0.21.2
        e:
            a1k26teqdgcsuqz01n30qlftjc8g6sm8:
                args:
                    - --num_step
                    - "100"
                    - --save_steps
                    - "50"
                    - --log_steps
                    - "10"
                    - --vocab_size
                    - "128"
                    - --d_model
                    - "64"
                    - --num_heads
                    - "4"
                    - --d_ff
                    - "128"
                    - --context_length
                    - "64"
                    - --num_layers
                    - "4"
                codePath: cs336_basics\trainer.py
                codePathLocal: cs336_basics\trainer.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "57670627328"
                        used: "49102966784"
                email: 760384579@qq.com
                executable: E:\LLM\CS336\assignment1-basics\.venv\Scripts\python.exe
                git:
                    commit: e60600a64d0137f40f14168498bdc1d20a74e5c7
                    remote: git@github.com:FlyingFish760/CS336-assignment1-basics.git
                gpu: NVIDIA GeForce MX450
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce MX450
                      uuid: GPU-9fa8c5ee-f6e2-5dc5-e0c0-7b91b322f017
                host: LAPTOP-KNVFV7GR
                memory:
                    total: "16969424896"
                os: Windows-10-10.0.19045-SP0
                program: E:\LLM\CS336\assignment1-basics\cs336_basics\trainer.py
                python: CPython 3.12.9
                root: E:\LLM\CS336\assignment1-basics
                startedAt: "2025-12-17T10:54:53.562825Z"
                writerId: a1k26teqdgcsuqz01n30qlftjc8g6sm8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.12.9
            "5": 0.21.2
            "8":
                - 3
            "12": 0.21.2
            "13": windows-amd64
max_learning_rate:
    value: 1e-05
steps:
    value: 100
